# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure('2') do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = 'ubuntu'
  config.vm.network "forwarded_port", guest: 22, host:2222, id: "ssh", auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host:8080, id: "web", auto_correct: true
  config.vm.define "localhost" do |l|
          l.vm.hostname = "localhost"
   end

   config.vm.provision "ansible" do |ansible|
      ansible.sudo = true
      ansible.playbook = "iv.yml"
      ansible.verbose = "v"
      ansible.host_key_checking = false
  end
end

